
spring:
  application:
    name: Gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: Auth-service
              uri: http://localhost:8081
              predicates:
                - Path=/auth/**


jwt:
  secret: 2ecf381a5a48d71f24a563c8b574fe2d9b896073f3fe3eb27e8da895623d7153